# Site
repository: csellington.github.io
favicon: images/favicon.ico

# Personal info
name: Christopher Ellington
title: Senior Network Architect
email: anon@localhost.net
website: csellington.github.io

# Social links
#twitter_username: facespics
github_username:  csellington
# dribbble_username: jekyll
facebook_username: csellington@sbcglobal.net
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: Interesting Facts About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network architect. As well as designing networks, I also have experience making helping people solve real world problems with technology. 

  My strengths include <b>Problem solving</b> <b>Networking</b> and <b>*nix</b>

# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience


# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  In addition to my interests in problem solving and networks, some of my other interests and hobbies are:
   - Parenting
   - Advocating
   - [ChiariBridges](https://chiaribridges.org/)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
